[package]
name = "ryde_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
sqlparser = { version = "0.43.1" }
syn = { version = "2", features = ["full", "extra-traits", "parsing"] }
rstml = { version = "0.11" }
